defaults: &default
  adapter: postgresql
  host: localhost
  encoding: utf8
  pool: 5

development:
  username: postgres
  password: postgres
  database: demo
  <<: *default

test:
  database: demo
  <<: *default

production:
  database: demo
  <<: *default